### ISSUE TITLE
2.7.7.1 punctuation parsing issue creating extra column in log files

### ISSUE THREAD

**Issue by eyarzebinski** [RoboTutorLLC/RoboTutor#413]
I'm seeing a column called "UJUZI" show up in 7 of the villages in the 11/23 data - in code drop 2 villages. From a few of the cherry-picked examples it looks like it's always in story hear #59, and a value of "<empty>" is stored in this column on the sentence "Alitaka kutumia ujuzi wake na marafiki wake kuleta mabadiliko kwao Mozambique." with student answer and expected answer both set to "elimu".

Kevin diagnosed it as stemming from an earlier request I made to remove the commas in a sentence because the punctuation was causing a parsing error during code drop 1. He discovered that the script that generated the storydata.json made these as one word.

Assigning to Kevin for followup. Not urgent as I can easily remove this column while I'm cleaning the data.

From Kevin:
![screen shot 2018-12-06 at 10 40 43](https://user-images.githubusercontent.com/38428578/49594293-8a1bc180-f943-11e8-84b7-ee39654ddc6e.png)

**Comment by JackMostow** [comment]
The culprit here and in some earlier STUCK bugs wasn't the comma but the absence of a space following it in the original story.txt when it was being narrated.  Searching every story.txt for commas not followed by spaces ought to find them.  Search storydata.json would find them but probably also e.g. "bla","foo".

**Comment by JackMostow** [comment]
This is a "Sleeping Beauty" bug.  In this one, the "spindles in the kingdom" are commas in a word.
As the folktale illustrates, trying to find and eliminate them all is not a reliable solution.
Alternatives:

a. Close the spindle factory, i.e. modify the script that generates storydata.json to insert spaces after word-internal commas.  Simply ensuring that every comma in the text has a comma after it won't be correct for "this example," for example.
+:  Fixes problem in future storydata.json.
-:  Requires regenerating all existing storydata.json.

b. Spindle-proof the princess, i.e. preprocess word-internal commas encountered at runtime.
+:  covers all cases
-;  must cover every step they affect, e.g. displaying the text, highlighting and crediting spoken words.
-:  tricky to fix segmentations of sentences already narrated, because the word boundaries are unknown.
